language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t silvercodex/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true silvercodex/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-406763999477"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
